### ISSUE TITLE
A f128 is not equal to itself

### ISSUE THREAD

**Issue by TheDan64** [jkarns275/f128#10]
Equivalence comparison seems to be off. For some reason this doesn't work:
```rust
let f = f128::new(4.1);

assert_eq!(f, f);
```

Which gets me:
```shell
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `4.09999999999999964472863211994990706`,
 right: `4.09999999999999964472863211994990706`', src/test.rs:20:5
```

**Comment by jkarns275** [comment]
Looks like I didn't use operator precedence correctly:
```
unsigned char eqq(Wrapper a, Wrapper b) {
    return (unsigned char) a.value == b.value;
}
```
should be:
```
unsigned char eqq(Wrapper a, Wrapper b) {
    return (unsigned char) (a.value == b.value);
}
```
Other cmp functions are similarly broken. Do note that comparing floats for equality is often times
bad practice (though there are times where testing for bit-level equality is useful).

**Comment by jkarns275** [comment]
Addressed by 2ecd27caff0702b0a2a9f899d39de94aaebe7a75
Ill add some tests to verify.

**Comment by TheDan64** [comment]
Awesome, thanks!

**Comment by jkarns275** [comment]
Tests added as of a2e9377e14aaea4260bc70642a8ba7302a24afa4.
