### ISSUE TITLE
-1=3.09434604738257827548018336997119785e-617

### ISSUE THREAD

**Issue by benruijl** [jkarns275/f128#15]
`-f128::one()`` gives 3.09434604738257827548018336997119785e-617 on my machine...

**Comment by jkarns275** [comment]
I've fixed this, by changing the way Neg works to:

```rust
fn neg(mut self) -> Self {
  let mut bits = self.inner_as_u128();
  bits ^= f128::SIGN_BIT.inner_as_u128();
  f128::from_raw_u128(bits)
}
```

Fixed in 8d04404f6671934a03b280addf12c3c5ff354845
