### ISSUE TITLE
Problems with sign and infinity checks

### ISSUE THREAD

**Issue by benruijl** [jkarns275/f128#16]
I don't think this is right (and my program crashes here too):

```
    fn signum(self) -> Self {
        match self.0[0] & 0x80 {
            0 => f128::INFINITY,
            1 => f128::NEG_INFINITY,
            _ => unreachable!(),
        }
    }
```
How can `self.0[0] & 0x80` ever be 1? It can be either 0 or 0x80.

Furthermore, this is not what the signum function is supposed to do at all!

**Comment by benruijl** [comment]
There were also issues with endianness. I have fixed the code in this commit: https://github.com/benruijl/f128/commit/f0b41e3372695ec6673e04279289726f9d35b23e

**Comment by jkarns275** [comment]
Yeah i think i meant to do self.0[0] & 0x80 != 0 . Thanks for the catch
