### ISSUE TITLE
Doesn't work with MSVC.

### ISSUE THREAD

**Issue by crlf0710** [jkarns275/f128#20]
Currently this library relies on libquadmath and libgfortran. None of which is available under MSVC environment.

**Comment by crlf0710** [comment]
Mmm... Why is this issue closed? A crate with a generic name like `f128` should be generically available.

**Comment by jkarns275** [comment]
https://github.com/boostorg/multiprecision/issues/13

**Comment by jkarns275** [comment]
This library is just wrapper around the gcc `libquadmath`  library. If you want to implement it in software or you know how to get msvc to link with `libquadmath.h`, I will be happy to accept a pull request.

**Comment by jkarns275** [comment]
I will keep this issue closed considering the project description
```
Bindings to GCC's __float128 type
```
