### ISSUE TITLE
Version bump on f128_internal and adjustment of dependencies within f128

### ISSUE THREAD

**Issue by josyoun** [jkarns275/f128#23]
I just ran a quick test with the new version 0.2.4 and noticed that it's not picking up the recently added assignment ops:

```
#![feature(proc_macro_hygiene)]
use ::f128::{f128,f128_inner};

fn main() {                    
    let mut x = f128!(0.45);
    let y = f128!(3.45);
    x %= y;                                                                     
} 
```

produces

```
error[E0368]: binary assignment operation `%=` cannot be applied to type `f128_internal::f128_t::f128`
 --> src/main.rs:13:5
  |
13|     x %= y;
  |     -^^^^^
  |     |
  |     cannot use `%=` on type `f128_internal::f128_t::f128`
  |
  = note: an implementation of `std::ops::RemAssign` might be missing for `f128_internal::f128_t::f128`
```
That said, the code works fine with my local version.  I think it's because the new code was actually in `f128_internal`, which `f128` depends on version `0.1.0`.  To fix this, I think we need to bump the version on `f128_internal` and then fix the dependency in `f128`.  Does that sound right?
```

**Comment by jkarns275** [comment]
Apologies, had to bump up the version of everything lol. `0.2.5` is the new version

**Comment by josyoun** [comment]
Laugh.  I hate releases as well.  Speaking of which, I can see the new version of `f128_internal` at `0.2.0` on [crates.io](https://crates.io/crates/f128_internal), but now `f128` [looks stuck](https://crates.io/crates/f128) at `0.2.4`.  I can see in the repository that the version was bumped.  Are you rate limited or did the publish to crates for `f128` get missed?

**Comment by jkarns275** [comment]
Sorry, it looks like I just forgot to run `cargo publish` for some reason.
I will publish it later today once i an access my home computer.

**Comment by jkarns275** [comment]
Okay I've published the new versions :)

**Comment by josyoun** [comment]
Awesome.  Works for me.  Thanks!
