### ISSUE TITLE
Build not working on Windows and VSCode

### ISSUE THREAD

**Issue by BillyDM** [jkarns275/f128#26]
Building on Windows 10 is not working. I think it has to do with the build script selecting the Visual Studio compiler instead of the MinGW-64 compiler. I did find quadmath.h located at

"C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include"

This is the error when I try to build it inside VS Code:

$ cargo build
   Compiling f128_internal v0.2.1
error: failed to run custom build command for `f128_internal v0.2.1`

Caused by:
  process didn't exit successfully: `C:\Dev\rack_afx_projects\Filters\src\target\debug\build\f128_internal-0e962bf0bcdf4100\build-script-build` (exit code: 1)
--- stdout
TARGET = Some("i686-pc-windows-msvc")
OPT_LEVEL = Some("0")
HOST = Some("i686-pc-windows-msvc")
CC_i686-pc-windows-msvc = None
CC_i686_pc_windows_msvc = None
HOST_CC = None
CC = None
CFLAGS_i686-pc-windows-msvc = None
CFLAGS_i686_pc_windows_msvc = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
DEBUG = Some("true")
running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX64\\x86\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-W4" "-Bstatic" "-lgfortran" "-lquadmath" "-FoC:\\Dev\\rack_afx_projects\\Filters\\src\\target\\debug\\build\\f128_internal-a45dd07cf074c702\\out\\src/f128.o" "-c" "src/f128.c"
cargo:warning=cl : Command line warning D9002 : ignoring unknown option '-Bstatic'
cargo:warning=cl : Command line warning D9002 : ignoring unknown option '-lgfortran'
cargo:warning=cl : Command line warning D9002 : ignoring unknown option '-lquadmath'
f128.c
src/f128.c(2): fatal error C1083: Cannot open include file: 'quadmath.h': No such file or directory
exit code: 2

--- stderr

error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX64\\x86\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-W4" "-Bstatic" "-lgfortran" "-lquadmath" "-FoC:\\Dev\\rack_afx_projects\\Filters\\src\\target\\debug\\build\\f128_internal-a45dd07cf074c702\\out\\src/f128.o" "-c" "src/f128.c" with args "cl.exe" did not execute successfully (status code exit code: 2).

**Comment by jkarns275** [comment]
This won't work on windows if you're using the MSVC release of rust. You need to use the GNU release, and ensure that the directory containing quadmath.h is passed as an include directory.
