### ISSUE TITLE
`epsilon()` returns f32 epsilon

### ISSUE THREAD

**Issue by benruijl** [jkarns275/f128#27]
`Float::epsilon()` should return `f128::EPSILON`, but instead it returns `f32::EPSILON`, because `Float for f128` is missing

```
    #[inline]
    fn epsilon() -> Self {
        f128::EPSILON
    }
```

**Comment by jkarns275** [comment]
Alright I added this function to the implementation of the Float trait in 0a95c1b272d4b89542d9721f24f330d9ab05382e. Will be included in the next version of the crate
