### ISSUE TITLE
Is proc_macro_hygiene still needed?

### ISSUE THREAD

**Issue by HadrienG2** [jkarns275/f128#30]
I recently ended up on this library, and noticed that it did not compile on stable due to use of the `proc_macro_hygiene` nightly feature.

Since there's been some movement on proc macro stabilization recently, I figured I'd just try to remove the feature gate and see what happens, and the result builds on stable and seems to produce correct mathematical results (validated against rug/MPFR).

Are you sure you still need this feature gate?

**Comment by jkarns275** [comment]
So I'm not entirely sure what i even used that for. This is where the proc_macro gets used to construct the f128 input macro
https://github.com/jkarns275/f128/blob/b5012f088d8caa383921d49ed144e6076aac8022/src/lib.rs#L9-L15

Does this look like it would compile on stable? (where f128_inner is a proc_macro)
I haven't been keeping up with the new versions of rust lately

**Comment by HadrienG2** [comment]
This looks like the "fn-like proc macro expanding to an expression or statement" feature gate, which was stabilized last summer through [this PR](https://github.com/rust-lang/rust/pull/68717) that [shipped in Rust 1.45](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1450-2020-07-16) last July.

And empirically speaking, I checked that if I just remove the feature gate, the crate builds on stable and seems to behave as intended.

**Comment by jkarns275** [comment]
Alright, I'll remove this and push out a new version of the crate today. Thanks for pointing this out.

**Comment by jkarns275** [comment]
Okay this was fixed with ebd3b2112c94bd20d056fbc209c900efa89ffce3

**Comment by HadrienG2** [comment]
Thanks!
