### ISSUE TITLE
License compatibility

### ISSUE THREAD

**Issue by koivunej** [jkarns275/f128#31]
Hi there!

Just stumbled upon this. It would appear that GCC quadmath library is under LGPL but this crate is MIT. Are the licenses compatible somehow? My understanding is that they are not: https://github.com/gcc-mirror/gcc/blob/6ff66d1ea48960fe96bb51a750c01135e65fe452/libquadmath/quadmath.h#L5-L9

**Comment by jkarns275** [comment]
This crate doesn't contain any of the source code from libquadmath so that doesn't actually matter.
