### ISSUE TITLE
Make alignment the same as __float128

### ISSUE THREAD

**Issue by benruijl** [jkarns275/f128#33]
Currently the alignment of the `f128` struct is 1. It's `C` equivalent `__float128` has an alignment of 16. Thus it is not safe to pass a `*mut f128` to a function in C that expects `__float128*`. By changing the alignment of `f128` to 16, passing pointers to a list of `f128` would become possible.

**Comment by jkarns275** [comment]
See 2065957660a7c6cb5148da550ef1b532ab8227da and 513964788f8e9720cc322060898196aadf64bc38
