### ISSUE TITLE
Optional including if gcc available?

### ISSUE THREAD

**Issue by oscargus** [jkarns275/f128#44]
This is maybe not an issue of the library as such, more asking for help related to the library.

I'm using f128 as part of a wave form viewer to convert a binary representation to the corresponding floating-point number and print it. This can of course be done without f128, but it still seems like a good idea to use an existing create.

Now, since f128 requires gcc, it would be nice if one can optionally disable using the f128 crate (and the code relying on it) if it is not used. I've tried things like (I need to use the git version):
```
[target.'cfg(any(target_env = "", target_env = "gnu"))'.dependencies]
f128 = { git = "https://github.com/jkarns275/f128.git" }
```
but to no avail. (As I understand it "gnu" is not really "gcc", although it often correlates. But not often enough...)

My goal is that the tool should compile with any compiler, but miss the quad-precision floating-point if not compiled with gcc.

Does anyone have a good idea how to obtain this?

If not, is there a (sensible) way to (re-)write the crate so that it doesn't kill the compilation (but doesn't work, of course) if gcc is not available? (`#ifdef` for the C-part will work, but maybe not worth the effort...)

**Comment by zachs18** [comment]
I don't know of any way to influence dependency resolution based on available binaries, and I don't think it would be good to have f128 just be empty if it can't find gcc.

It would probably be easiest to just have `f128` as an optional-dependency/feature in your crate, e.g.

```toml
[dependencies]
f128 = { version = "...", optional = true }
```

(Example https://github.com/zachs18/mandelbrot-rs/tree/main/mandelbrot though I explicitly declare the feature here)

With this, users of your crate can enable the implicitly declared `f128` cargo feature to enable using f128, and you can use `#[cfg(feature = "f128")]` in your crate on code that requires f128. You can also make it an enabled-by-default feature with

```toml
[features]
default = ["f128"]
```

**Comment by oscargus** [comment]
Ahh, thanks! I'm not that well-versed in Rust, but that clearly makes sense!
